name: test project
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: getcode
        uses: actions/checkout@v3
      - name: install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install dependencies
<<<<<<< HEAD
        run: npm install
=======
        run: npm
>>>>>>> 23dab32b2f13962a75aa2cc5c6d5b2761e0efd19
      - name: run tests
        run: npm test
