name: test project
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: getcode
        uses: actions/checkout@v3
      - name: install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install dependencies
        run: npm install
      - name: run tests
        run: npm test
